name       : python-wcwidth
version    : 0.1.7
release    : 2
source     :
    - https://pypi.python.org/packages/55/11/e4a2bb08bb450fdbd42cc709dd40de4ed2c472cf0ccb9e64af22279c5495/wcwidth-0.1.7.tar.gz : 3df37372226d6e63e1b1e1eda15c594bca98a22d33a23832a90998faa96bc65e
license    : MIT
component  : programming.python
summary    : Measures number of Terminal column cells of wide-character codes
description: |
    Measures number of Terminal column cells of wide-character codes
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
