name       : python-wcwidth
version    : 0.2.5
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/w/wcwidth/wcwidth-0.2.5.tar.gz : c4d647b99872929fdb7bdcaa4fbe7f01413ed3d98077df798530e5b04f116c83
license    : MIT
component  : programming.python
summary    : Measures number of Terminal column cells of wide-character codes
description: |
    Measures number of Terminal column cells of wide-character codes
builddeps  :
    - pkgconfig(python3)
    - python-backports.functools_lru_cache
    - python-pytest # check (warning: circular)
    - python-setuptools
rundeps    :
    - backports.functools-lru-cache
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test pytest
    %python3_test pytest3
